inputs:
  - name: input_images # i.e. images (bunch of images in a folder)
    type: collection
    subtype: [grayscale_image, rgb_image, multichannel_image]
    description: "supported input images"
    path: "path/to/image"
    format: [png, jpg, jpeg, ometiff, tif]
  - name: custom_trained_model
    type: file
    subtype: unix executable file
    description: "custom trained model file for xyz (eg. nuclei, cyto, etc.)"
    path: "path/to/model"
    format:  # discuss

outputs:
  - name: output_images # i.e. folder containing images
    type: collection
    subtype: [grayscale_image, rgb_image, multichannel_image]
    description: "xyz output images, if abc parameters are provided"
    path: "path/to/output"
    format: [png, jpg, jpeg, ometiff, tif]
    depends_on: 
      - list of name of input parameters that affects this output
      - abc
      - xyz
  - name: output_files # 
    type: files
    subtype: [csv | excel | binary | log | special]
    description: "output files"
    path: "path/to/output"
    format: ("csv", "tsv", "psv") | ("xlsx", "xls") | ("parquet", "feather") | ("log", "txt", "json", "xml", "yaml", "csv", "tsv") | ("h5", "hdf5")
    compressed: [True, False]
    depends_on: 
      - list of name of input parameters that affects this output
      - abc
      - xyz
  - name: array_output
    type: array
    subtype: numpy
    description: "defines the array-based outputs generated by the algorithm"
    path: "path/to/output"
    format: [npy, npz]
    compressed: [True, False]
    depends_on: 
      - list of name of input parameters that affects this output
      - abc
      - xyz