[workspace]
authors = ["Helia Gohar <helia.goharbvg@gmail.com>"]
channels = ["conda-forge"]
name = "morphem_inference"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
pip = ">=24,<26"
numpy = ">=2.4.6,<3"
pillow = ">=12.3.0,<13"
tifffile = ">=2026.3.3,<2027"
pandas = ">=2.0,<3"

[feature.cpu.dependencies]
pytorch-cpu = ">=2.4,<2.5"
torchvision = ">=0.19,<0.20"

[feature.cpu.pypi-dependencies]
transformers = ">=4.56.1, <5"

[environments]
cpuenv = ["cpu"]
