inputs:
  - name: input_images
    type: image
    label: "Drag and drop all images to be analyzed"
    subtype: 
      - grayscale
      - color
      - binary
      - labeled
    description: "Upload all images to be analyzed"
    cli_tag: "--folder"
    cli_order: 0
    default: "directory"
    optional: False
    format: 
      - tiff
      - ometiff
      - png
      - jpg
      - jpeg
    folder_name: "/bilayers/input_images"
    file_count: multiple
    section_id: "inputs"
    mode: "beginner"
    depth: True
    timepoints: True
    tiled: True
    pyramidal: True

outputs:
  - name: segmented_images
    type: image
    label: "Segmented Images"
    subtype: 
      - grayscale
      - color
      - binary
      - labeled
    description: "Segmented images"
    cli_tag: "None"
    cli_order: 0
    default: "directory"
    optional: False 
    format: 
      - tiff
      - ometiff
    folder_name: "/bilayers/input_images" # discuss
    file_count: multiple
    section_id: "outputs"
    mode: "beginner"
    depth: True
    timepoints: True
    tiled: True
    pyramidal: True
    
parameters:
  # - name: input_images
  #   type: files
  #   label: "Drag and drop all images to be analyzed"
  #   description: "Upload all images to be analyzed"
  #   file_count: multiple
  #   default: "directory"
  #   cli_tag: "--folder"
  #   optional: False
  #   section_id: "input-args"
  #   folder_name: "/bilayers/input_images"
  #   mode: "beginner"
  - name: threshold_method
    type: radio
    label: "Select a Threshold Method"
    description: "Select a threshold method to segment the image"
    options:
      - label: "otsu"
        value: "otsu"
      - label: "li"
        value: "li"
    default: "otsu"
    cli_tag: "--threshold_method"
    optional: False
    section_id: "input-args"
    mode: "beginner"
  - name: min_diameter
    type: float
    label: "Object Minimum Diameter Size"
    description: "Minimum diameter of objects in pixels"
    default: 5
    cli_tag: "--min_size"
    optional: False
    section_id: "input-args"
    mode: "beginner"
  - name: max_diameter
    type: float
    label: "Object Maximum Diameter Size"
    description: "Maximum diameter of objects in pixels"
    default: 20
    cli_tag: "--max_size"
    optional: False
    section_id: "input-args"
    mode: "beginner"
  - name: save_dir
    type: textbox
    label: "Save Directory"
    description: "directory to save output files"
    output_dir_set: True
    default: "/bilayers/input_images"
    cli_tag: "--save_dir"
    optional: True
    section_id: "output-args"
    mode: "advanced"

display_only:

    
exec_function: 
  name: "generate_cli_command"
  script: "classical_segmentation"
  module: "algorithms.classical_segmentation"
  cli_command: "python -m classical_segmentation"
  hidden_args:

docker_image:
  org: bilayer
  name: classical_segmentation
  tag: "1.0.0"
  platform: "linux/arm64"

algorithm_folder_name: "classical_segmentation"

citations:
  algorithm: 
    - name: "Classical Segmentation"
      doi: doi_number
      license: license_details
      description: "Segments images using classical thresholding methods : Otsu and Li"
