inputs:
  - name: input_images
    type: image
    subtype: 
      - grayscale
      - color
      - binary
      - labeled
    description: "Input images to be analyzed"
    optional: False
    path: "/bilayers/input_images"
    format: 
      - tiff
      - ometiff
      - png
      - jpg
      - jpeg
    collection: True
    z: True
    t: True
    tiled: True
    pyramidal: True

outputs:
  - name: segmented_images
    type: image
    subtype: 
      - grayscale
      - color
      - binary
      - labeled
    description: "Segmented images"
    optional: False 
    path: "/bilayers/input_images" # discuss
    format: 
      - tiff
      - ometiff
    collection: True
    z: True
    t: True
    tiled: True
    pyramidal: True

parameters:
  - name: input_ images
    type: files
    label: "Drag and drop all images to be analyzed"
    description: "Upload all images to be analyzed"
    file_count: multiple
    default: "directory"
    cli_tag: "--folder"
    optional: False
    section_id: "input-args"
    folder_name: "/bilayers/input_images"
    mode: "beginner"
  - name: threshold_method
    type: radio
    label: "Select a Threshold Method"
    description: "Select a threshold method to segment the image"
    options:
      - label: "otsu"
        value: "otsu"
      - label: "li"
        value: "li"
    default: "otsu"
    cli_tag: "--threshold_method"
    optional: False
    section_id: "input-args"
    mode: "beginner"
  - name: min_diameter
    type: float
    label: "Object Minimum Diameter Size"
    description: "Minimum diameter of objects in pixels"
    default: 5
    cli_tag: "--min_size"
    optional: False
    section_id: "input-args"
    mode: "beginner"
  - name: max_diameter
    type: float
    label: "Object Maximum Diameter Size"
    description: "Maximum diameter of objects in pixels"
    default: 20
    cli_tag: "--max_size"
    optional: False
    section_id: "input-args"
    mode: "beginner"
  - name: save_dir
    type: textbox
    label: "Save Directory"
    description: "directory to save output files"
    output_dir_set: True
    default: "/bilayers/input_images"
    cli_tag: "--save_dir"
    optional: True
    section_id: "output-args"
    mode: "advanced"

display_only:

results:
  - name: output_dir
    type: files
    label: "Download Output"
    description: "Download the output files"
    file_count: multiple
    cli_tag: "None"
    optional: True
    section_id: "output-args"
    mode: "beginner"
    
exec_function: 
  name: "generate_cli_command"
  script: "classical_segmentation"
  module: "algorithms.classical_segmentation"
  cli_command: "python -m classical_segmentation"
  hidden_args:

docker_image:
  org: bilayer
  name: classical_segmentation
  tag: "1.0.0"

algorithm_folder_name: "classical_segmentation"

citations:
  algorithm: 
    - name: "Classical Segmentation"
      doi: xxxx
      description: "Segments images using classical thresholding methods : Otsu and Li"
