FROM pytorch/pytorch:2.1.1-cuda12.1-cudnn8-runtime

RUN apt-get -y update && apt-get -y upgrade && apt-get install -y python3-pip git curl

WORKDIR /

RUN git clone https://github.com/instanseg/instanseg.git

WORKDIR instanseg

RUN git checkout b9c9d6b

RUN conda env create --file env.yml

RUN conda run -n instanseg pip install -e .

SHELL ["conda", "run", "-n", "instanseg", "/bin/bash", "-c"]

ENTRYPOINT ["conda", "run", "-n", "instanseg"]
