FROM pytorch/pytorch:2.1.1-cuda12.1-cudnn8-runtime

RUN apt-get -y update && apt-get -y upgrade && apt-get install -y python3-pip git

WORKDIR /

RUN git clone https://github.com/instanseg/instanseg.git

WORKDIR instanseg

RUN git checkout b9c9d6b

RUN pip install -e .
