[project]
name = "instanseg-torch"
description = """
Pixi definition for instanseg-torch
"""
platforms = ["linux-64"]
version = "0.0.5"
channel-priority = "disabled"
channels = ["conda-forge", "pytorch", "nvidia" ]

[feature.cuda]
channels = ["conda-forge", "pytorch", { channel = "nvidia", priority = 2 }, { channel = "nvidia/label/cuda-12.3.1", priority = 3 }]

[dependencies]
python = "3.9.*"
numpy = "1.26.4"
tqdm = "4.66.1"
matplotlib = "3.8.2"
colorcet = "3.0.1"
fastremap = "1.14.0"
rasterio = "1.3.9"
tifffile = "2023.12.9"
scikit-image = "0.22.0"
aicsimageio = "4.*"
zarr = ">=2.6.0,<2.16.0"
imageio = ">=2.11.0,<2.28.0"
tiffslide = "2.4.0"
imagecodecs = "2024.1.1"
seaborn = "0.13.2"
scipy = "1.11.4"
scikit-learn = "1.3.2"
hyperopt = "0.2.7"
einops = "0.7.0"
"bioimageio.core" = "0.5.11"
"bioimageio.spec" = "0.4.9"
onnx = "1.15.0"
tensorboard = "2.17.0"
stardist = "0.8.5"
pytorch = "2.1.1"
torchvision = "0.16.1"
pip = "23.3.2"

[feature.cpu.dependencies]
cpuonly = "*"

[feature.cuda.dependencies]
pytorch-cuda = "==12.1"

[feature.cuda.pypi-dependencies]
cupy-cuda12x = "==13.3.0"
cucim-cu12 = "==24.8.0"

[pypi-dependencies]
bioio = "==1.1.0"
slideio = "==2.6.3"
torchstain = "==1.3.0"
opencv-python-headless = ">=4.5.1"
kornia = "==0.7.0"
monai = "==1.3.0"
edt = "==2.4.1"
instanseg-torch = { path = "/instanseg", editable = true }

[environments]
cpuenv = { features = ["cpu"] }
cudaenv = { features = ["cuda"] }
