inputs:
  - type: Files
    file_count: multiple
    label: "Drag and drop all images to be analyzed"
  - type: Radio
    label: "Select a Threshold Method"
    options:
      - label: "Otsu"
        value: "Otsu"
      - label: "Li"
        value: "Li"
  - type: Number
    label: "Object Minimum Diameter Size"
    value: 5
    min: 5
    interactive: true
  - type: Number
    label: "Object Maximum Diameter Size"
    value: 20
    max: 30
    interactive: true

output:
  - type: Files
    file_count: multiple
    label: "Download Output"

exec_function: 
  name: "example_function"
  script: "threshold"
  module: "Algorithms.threshold"