name: "✨ Feature request ✨"
description: Suggest an idea for this project
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a feature request! Please provide as much detail as possible to help us fully understand your idea.
  - type: checkboxes
    id: duplicate_check
    attributes:
      label: Have you searched for similar issues?
      description: Please ensure that your feature request is not a duplicate of an existing issue
      options:
        - label: I have searched the existing issues and did not find a duplicate
          required: true
  - type: dropdown
    id: feature_type
    attributes:
      label: What type of feature are you requesting?
      description: Select the type of feature you're requesting
      options:
        - "Spec enhancement"
        - "New DL Algorithm"
        - "New Interface"
        - "CLI flag Pattern"
        - "Something else"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Feature Details
      description: A detailed description of the feature you are requesting
      placeholder: Describe the feature you would like to request. For example, Adding support for type=dropdown, integrating a new DL algorithm like Stardist, introducing a new interface like Streamlit, or requesting a CLI flag pattern like -t=value_with_single_dash
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here
      placeholder: Add any other context or screenshots
    validations:
      required: false