name: "✨ Feature request ✨"
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to open a feature request! Please provide us with as much detail as possible to help us understand your idea
  - type: checkboxes
    id: duplicate_check
    attributes:
      label: Have you searched for similar issues?
      description: Please ensure that your feature request is not a duplicate of an existing issue
      options:
        - label: I have searched the existing issues and did not find a duplicate
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A detailed description of the feature you are requesting
      placeholder: Describe the feature you would like to see
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here
      placeholder: Add any other context or screenshots
    validations:
      required: false