inputs:
  - type: Files
    file_count: multiple
    label: "Drag and drop all images to be analyzed"
  - type: Radio
    label: "Select a Threshold Method"
    options:
      - label: "Otsu"
        value: "Otsu"
      - label: "Li"
        value: "Li"
  - type: Number
    label: "Object Minimum Diameter Size"
    value: 5
    min: 5
    interactive: true
  - type: Number
    label: "Object Maximum Diameter Size"
    value: 20
    max: 30
    interactive: true

outputs:
  - type: Files
    file_count: multiple
    label: "Download Output"

exec_function: 
  name: "example_function"
  script: "threshold"
  module: "src.Algorithms.threshold"

docker-image:
  name: "threshold-image"

folder_name: "threshold"

citations:
  Bilayers:
    - name: "Bilayers"
      license: xxxxx
      description: "GUI interfaces for deep learning-based cell segmentation algorithms"
  Jupyter:
    - name: "Jupyter"
      doi: 10.1109/MCSE.2007.53
      description: "Interactive, code-driven documents for data analysis and visualization"
  Gradio:
    - name: "Gradio"
      doi: 10.48550/arXiv.1906.02569
      description: "A simple web interface for deploying machine learning models"
  Algorithm: 
    - name: "Threshold"
      doi: xxxx
      description: "This is threshold algorithm"
