name: Docker-Build Pipeline

on:
  # TODO: disable until caching system is implemented
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   types: [opened, reopened, synchronize, ready_for_review, review_requested]
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      runner:
        description: 'Select the runner to use'
        required: true
        default: 'self-hosted'
        type: choice
        options:
          - self-hosted
          - ubuntu-latest
      algorithm:
        description: 'Select the algorithm to build'
        required: true
        default: 'classical_segmentation cellpose_inference instanseg_inference gaussian_smoothing'
        type: string
      interface:
        description: 'Select the interface to build'
        required: true
        default: 'gradio jupyter'
        type: string
      bump_type:
        description: 'Version bump type'
        required: false
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  check-machine:
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Check Runner Architecture
        run: |
          echo "Running 'uname -m' to see architecture..."
          uname -m

  lint-validate-docs:
    name: Lint, Validate, and Generate Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install linkml

      - name: Lint code with LinkML
        run: |
          chmod +x scripts/lint.sh
          ./scripts/lint.sh

      - name: Validate schema with LinkML
        run: |
          chmod +x scripts/validate.sh
          ./scripts/validate.sh

      - name: Auto generate docs with LinkML
        run: |
          chmod +x scripts/gendoc.sh
          ./scripts/gendoc.sh

  build:
    name: Build ${{ github.event.inputs.algorithm }} (${{ github.event.inputs.interface }})
    runs-on: ${{ github.event.inputs.runner }}
    needs: lint-validate-docs
    if: github.event_name == 'workflow_dispatch'   # only run build when manually triggered

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install nox
        run: |
          pip install nox

      - name: Run targeted Docker build
        run: |
          chmod +x ./scripts/build_docker.sh
          ./scripts/build_docker.sh \
            --algorithm ${{ github.event.inputs.algorithm }} \
            --interface ${{ github.event.inputs.interface }}
