name: Temporary Pipeline

on:
  push:
    branches:
      - pipeline_fix

jobs:
    try-which-machine:
        name: Try which machine
        runs-on: ubuntu-latest

        steps: 
            - name: Run architecture check
              run: |
                echo "Runner architecture: $(uname -a)"
                docker run --rm ubuntu:latest uname -a