name: Test

on:
  push:
  pull_request:
  # TODO: disable until caching system is implemented
  # pull_request:
  #   types: [opened, reopened, synchronize, ready_for_review, review_requested]
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  testing-validation-of-config:
    name: Running tests for validation of config files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.10.0
        with:
          environments: dev
          locked: true
          cache: true

      - name: Run tests
        run: |
          pixi run -e dev bash scripts/test_docker.sh
          pixi run -e dev nox -s test_pytest
